workflows:
  my-workflow:
    unity-android-release-workflow:

     name: Unity Android release workflow
    
    max_build_duration: 120
    
    environment:
      groups:
        - unity
      vars:
        - ...
        
    scripts:
      - ...
    artifacts:
      - ...
    publishing:
      - ...
